services: 
    mongodb:
      image: mongo
      container_name: mongo_db
      ports: 
        - "27017:27017"
      volumes:
        - mongo:/data/db
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root 
        - MONGO_INITDB_ROOT_PASSWORD=pass 
    
    postgresql:
      container_name: postgresql_db
      image: postgres:15
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: product_db
        POSTGRES_HOST_AUTH_METHOD: trust  
        
      volumes:
        - postgres:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - microservices


volumes:
    mongo:
    postgres:
networks:
    microservices:
      driver: bridge
        