Spring:
   data:
      mongodb:
         host: localhost
         port: 27017
         database: custmomer_db
         username: root
         password: pass
         authentication-database: admin
logging:
  level:
    root: INFO
    com.seba.microservices: WARN
  pattern: 
     console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'  
     file:    '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n' 
  file:
       name: logs/customer-microservices.log
       max-size: 10MB
       max-history: 30
server:
    port: 8091