server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db?serverTimezone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:  
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect